import pandas
df=pandas.read_csv("C:/Users/SAICHARAN/Documents/mobile_sales_data.csv")
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
print(df.isnull().sum())
df['core_specification']=df['core_specification'].fillna('unknown')
df['ssd']=df['ssd'].fillna('unknown')
df=df.drop_duplicates()
df['inward_date']=pandas.to_datetime(df['inward_date'])
df['dispatch_date']=pandas.to_datetime(df['dispatch_date'])
df.info()
df['price']=df['price'].astype('float')
df.info()
df.to_csv("C:/Users/SAICHARAN/Documents/cleaned_sales_data.csv",index=False)
